# Generated by Django 4.2.16 on 2024-09-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('IDname', models.IntegerField()),
                ('Location', models.CharField(max_length=10)),
                ('Shift_Start_Date', models.DateField()),
                ('Shift_Start_Time', models.TimeField()),
                ('Shift_End_Time', models.TimeField()),
                ('Shift_End_Date', models.DateField()),
            ],
        ),
    ]
